DB_TYPE_KEY = "DB_TYPE"

MYSQL_HOST_KEY = "MYSQL_HOST"
MYSQL_PORT_KEY = "MYSQL_PORT"
MYSQL_USER_KEY = "MYSQL_USER"
MYSQL_PASSWORD_KEY = "MYSQL_PASSWORD"
MYSQL_DB_KEY = "MYSQL_DB"

DM_HOST_KEY = "DM_HOST"
DM_PORT_KEY = "DM_PORT"
DM_USER_KEY = "DM_USER"
DM_PASSWORD_KEY = "DM_PASSWORD"
DM_DB_KEY = "DM_DB"
